### ISSUE TITLE
Countdown isn't timezone aware

### ISSUE THREAD

**Issue by russtacular** [lauren/laurenandjeremy#6]
I'm very confused by your countdown clock and now have no idea when the date of the event actually is. I originally loaded the page in New York (EDT) and saw that it's a mere "1 year, 0 months, 21 days, 14 hours, 49 minutes, 42 seconds" away. However, I then mentally travelled to Gorakhpur, India and took my computer's timezone setting with me and it was still "1 year, 0 months, 21 days, 14 hours, 49 minutes, 42 seconds" in the future.

Please help, I don't want to be 9:30 hours early/late!

**Comment by lauren** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8643950-126343652_8-s1-v1.png?transparent=1&width=246)

**Comment by lauren** [comment]
Submit a pull request @russtacular

**Comment by lauren** [comment]
THE WEDDING IS OVER
